import "@/app/globals.css";
import Navbar from "@/components/navbar";

export const metadata = {
  title: "Practical Assignment App",
  description: "Generated by create next app",
};

export default function PublicPagesLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-100">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
